Fix test compilation error.
fix a compilation error that caused by missing header files

---
test/script_standard_tests.cpp: 在成员函数‘void script_standard_tests::script_standard_Solver_success::test_method()’中:
test/script_standard_tests.cpp:105:5: 错误：‘CSHA256’在此作用域中尚未声明
     CSHA256().Write(&redeemScript[0], redeemScript.size())
     ^~~~~~~
test/script_standard_tests.cpp:105:5: 附注：suggested alternative: ‘CSHA3_256’
     CSHA256().Write(&redeemScript[0], redeemScript.size())
     ^~~~~~~
     CSHA3_256